runtime: nodejs
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
#handlers:
#- url: /(.*)
  #script: server.js
  #secure: optional
  #http_headers:
  #  Access-Control-Allow-Origin: http://alarmbuddy.live